export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS"
export const FOUND_USER = "FOUND_USER"
export const UPDATE_USER = "UPDATE_USER"
export const NOT_FRIENDS = "NOT_FRIENDS"
export const FRIENDS_FOUND = "FRIENDS_FOUNDS"
export const REMOVE_FRIENDS = "REMOVE_FRIENDS"
export const ADD_FRIENDS = "ADD_FRIENDS"
export const CANCEL_POTLUCK = "CANCEL_POTLUCK"
export const CREATE_POTLUCK = "CREATE_POTLUCK"
export const POTLUCKS_FOUND = "POTLUCKS_FOUND"
export const UPDATE_POTLUCK ="UPDATE_POTLUCK"
CANCEL_POTLUCK
types.CREATE_POTLUCK
POTLUCKS_FOUND
UPDATE_POTLUCK
